import numpy as np 
arr1=np.array([2,4,6,8,10])
arr2=np.array([1,3,5,7,9])
print("Array 1 Elements: ",arr1)
print("Array 2 Elements: ",arr2)
print("\n Addition of the arrays: ",np.add(arr1,arr2))
print("\n Subtraction of the arrays: ",np.subtract(arr1,arr2))
print("\n Multiplication of the arrays: ",np.multiply(arr1,arr2))
print("\n Division of the arrays: ",np.divide(arr1,arr2))
print("\n Maximum arrays elements: ",np.maximum(arr1,arr2))
print("\n Minimum arrays elements: ",np.minimum(arr1,arr2))
print("\n Sum of array1 elements: ",np.sum(arr1))
print("\n Mean of array1 elements: ",np.mean(arr1))
print("\n Median of array1 elements: ",np.median(arr1))
print("\n Standard Deviation of array1 elements: ",np.std(arr1))
