import sqlite3
conn=sqlite3.connect('Employee1.db')
cursor=conn.cursor()
cursor.execute('''CREATE TABLE IF NOT EXISTS employee1(name TEXT NOT NULL, age INTEGER, desg TEXT)''')
cursor.execute('INSERT INTO employee1 VALUES("Rahul",40,"MANAGER")')
cursor.execute('INSERT INTO employee1 VALUES("Rita",35,"Sr.developer")')
cursor.execute('INSERT INTO employee1 VALUES("Arush",43,"DB designer")')
conn.commit()
def display():
    cursor.execute('SELECT * FROM employee1')
    records=cursor.fetchall()
    print("NAME\tAGE\tDESIGNATION")
    print("-"*27)
    for rows in records:
        print(f"{rows[0]}\t{rows[1]}\t{rows[2]}")
display()
cursor.execute('UPDATE employee1 SET desg="Tech lead" where name="Rita"')
conn.commit()
cursor.execute('DELETE FROM employee1 WHERE name="Rahul"')        
conn.commit()
print("\n Table data after update and delete: ")
display()
cursor.execute('DROP TABLE employee1')
conn.commit()
conn.close()
